language: cpp

os:
  - linux
  - osx

branches:
  only:
    - master
    - test

addons:
  apt:
    packages: &common_packages
      - lcov
      - cmake
      - make
      - gdb

env:
  jobs:
    - BOGUS_JOB=true

jobs:
  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-7 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-7
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-8 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-8
    - os: linux
      dist: xenial
      env: CXX_COMPILER=g++-8 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *common_packages
            - g++-8
    - os: linux
      env: CXX_COMPILER=clang++-6.0 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - *common_packages
            - clang-6.0
            - g++-7
    - os: linux
      env: CXX_COMPILER=clang++-7 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - *common_packages
            - clang-7
            - g++-7
    - os: linux
      env: CXX_COMPILER=clang++-8 CXXSTD=c++17
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - *common_packages
            - clang-8
            - g++-7
    - os: osx
      osx_image: xcode11.2
      env: CXX_COMPILER=clang++ CXXSTD=c++17

install:
  - cd ..
  - cd baryonyx
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CXXFLAGS="-std=$CXXSTD" cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_MAKEFILE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug .. ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then CXXFLAGS="-std=$CXXSTD -g -O0 --coverage -fprofile-arcs -ftest-coverage" cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_COLOR_MAKEFILE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None .. ; fi

script:
  - make
  - sudo make install
  - ctest -E testoptimizer

after_success:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then cd ${TRAVIS_BUILD_DIR} ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --directory . --capture --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --remove coverage.info 'external/*' --output-file coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then lcov --list coverage.info ; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then bash <(curl -s https://codecov.io/bash) ; fi

notifications:
  email:
    on_success: always
